# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HWLMutableLabel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HWLMutableLabel
  pod 'YYCategories', :path => '../../podLibrary/YYCategories'

  target 'HWLMutableLabelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HWLMutableLabelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
